name: GitHub Build
run-name: ${{ github.actor }} is building
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get zig
        uses: mlugg/setup-zig@v2
      - name: Get upx
        uses: samyfodil/upx-action@v1.0.3
      - name: Install zip
        run: sudo apt install -y zip
      - name: Run build
        run: ./build.sh --release
      - name: list bin
        run: ls -la ./bin/
      - name: Upload csvcut-x86_64-windows
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: csvcut-x86_64-windows
          path: ./bin/csvcut-x86_64-windows.zip
          compression-level: 0
          overwrite: true
      - name: Upload csvcut-x86_64-linux
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: csvcut-x86_64-linux
          path: ./bin/csvcut-x86_64-linux.gz
          compression-level: 0
          overwrite: true
      - name: Upload csvcut-aarch64-linux
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: csvcut-aarch64-linux
          path: ./bin/csvcut-aarch64-linux.gz
          compression-level: 0
          overwrite: true
